on: [workflow_dispatch, push]

jobs:
  task:
    runs-on: ubuntu-latest
    
    steps:
      - name: List Repo Workflows
        id: get_wfs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/actions/workflows
          ref: refs/heads/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.get_wfs.outputs.data }}"
